### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by ThexXTURBOXx** [ThexXTURBOXx/studip-app-uni-passau#1]
- [x] Cleanup for first version release 9d46afa42a97662ff6a90991a2ac262503405956
 - [x] Only update, when there is internet connection and the setting is set 8239a5998c86168671eb3063c58f19dab435e052
 - [x] Add cache for mensa plan and schedule 8239a5998c86168671eb3063c58f19dab435e052
 - [x] Add Settings 98fd5130bff0b2935090da52ac63426ead428f69
 - [x] Add credits and dependencies in Readme d7f4fba4b372c644324b5c703b012afc27b0dfc9
 - [x] Fix finishing of Activities 4a0c0460615f176a8d5f7791843ce6ea358d64d8
 - [x] Add source link in About screen 360eb055bcf4eef8249dbfc9759fba2bb2cef932
 - [x] Add About screen c090d30c3dc07d8c1290e1b6cf6bf5f6d88e3a8b
 - [x] Add Report bugs feature 9e222a7b0dcd5e53e5205a9268d2753a2811c54f
 - [x] Restrict date changing in MensaActivity to received data 2bb13d64dc6ad3f8cf78ccf13f3b28b5456f80ad
 - [x] Add Stud.IP link 34dc1004a3c264bd052dbe8633f14b9c8204d093
 - [x] Make icons for FoodProperties working 2cd92c0d45b646f5239aad5f11241762134d10b1
 - [x] Add formatting to Food prices in MensaActivity c6c32551cfefc213e3fbb1af71d54f63469fa31a
 - [x] Global navigation drawer or just take the data from it and apply it in every activity 75e670e57cea48792d9d69a80711b0698977a218
 - [x] Add "tomorrow" string to ScheduleActivity 77a734373c6cc35e73266761f65f518a1ead65d8
 - [x] Add manual refresh possibility 32ccdc65bd9e2e2725f5eeebd514370f6088ef5c
 - [x] Fix MensaActivity --> When the user changes day while updating, the updates are not applied 32ccdc65bd9e2e2725f5eeebd514370f6088ef5c
 - [x] Add indicators for loading in Mensa Activity/Schedule Activity 32ccdc65bd9e2e2725f5eeebd514370f6088ef5c
 - [x] Add loading state to loading screen after login 2304500763cbbece9bdd3ad41ebf5275fba6b9be
 - [x] Animate navigation drawer item 7a0e3148f2764b41d936c6ff34e5f8532a4794a6

**Comment by ThexXTURBOXx** [comment]
Done, bug reports may be useful from now on
