### ISSUE TITLE
TODO 0.3

### ISSUE THREAD

**Issue by ThexXTURBOXx** [ThexXTURBOXx/studip-app-uni-passau#21]
For the initial 0.3 release, we need to do those things yet:
 - [x] Fix About Screen Button tints for older Android devices (4a1828504363e8d1a26533aedd0b18d32cbcd588)
 - [x] Only allow to select valid dates in the schedule calendar (8215d53ae3b99f7f4738fad1e1bb0b202387e795)
 - [x] Fix transparency color calculation (02be8eeb60f19edfb8d5a44df9b8c28d03681c11)
 - [x] Fix Navbar and Settings Screen back button (seems to only affect the About screen) (10c07a94ecd6697796af0b91beb5b83d80a636e2)
 - [x] Ask non-colorblind people about the colors
 - [ ] Reassure, that all texts/buttons and so on use the correct colors
 - [x] Fix Shortcut Icons (377ffb95f66d7f010ee2e10b6e47f09e4cad1e3a)
 - [x] Fix Travis (Fixed itself appearently... Bug maybe?)
 - [ ] Fix crash when switching between dark/light mode
 - [ ] Reassure, that all Time Zones are set correctly
 - [ ] Add Mensa close time preference

For the after-releases in the 0.3 series, this is to do:
 - [ ] #20 Rewrite Mensa Plan 
 - [ ] Include credits in the app as another screen
 - [ ] _Maybe_ add Horizontal scroll to Schedule
