### ISSUE TITLE
TODO 0.0.3

### ISSUE THREAD

**Issue by ThexXTURBOXx** [ThexXTURBOXx/studip-app-uni-passau#5]
- [x] Add Categories to Schedule (Lecture / Exercises / ...) f2038f454d7fc61cc969323749211076b2dfe3f9
 - [x] Fix "Load more..."-button when offline 8aebaa60a463c7caea1e670f1f1cc84a4b61c8ea
 - [x] Save 4 weeks in advance and load only weeks saved in variable 8aebaa60a463c7caea1e670f1f1cc84a4b61c8ea
 - [x] Fix support for old Android verisons 388dcc48377b938553d30e6c8320162896dc8b1d 731ea5c031c19aaa63c63d0144d0c4390712eb7d
